[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "2.2.1"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
axum = "0.8.1"
